workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Flutter bağımlılıklarını yükle
        script: flutter pub get
      - name: APK oluştur
        script: flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - erenoizm@gmail.com
        notify:
          success: true
          failure: true
