workflows:
  android-workflow:
    name: Neon Galeri Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Proje oluştur ve APK al
        script: |
          flutter create -t app tempproject
          cp -r lib tempproject/
          cd tempproject
          python3 -c "
content = open('pubspec.yaml').read()
content = content.replace('sdk: \'>=3.5.0 <4.0.0\'', 'sdk: \'^3.11.0\'')
content = content.replace('sdk: \'>=3.0.0 <4.0.0\'', 'sdk: \'^3.11.0\'')
deps = '''  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.9.0
  shared_preferences: ^2.2.2
'''
content = content.replace('  flutter:\n    sdk: flutter\n', '  flutter:\n    sdk: flutter\n' + deps)
open('pubspec.yaml', 'w').write(content)
print(open('pubspec.yaml').read())
"
          flutter pub get
          flutter build apk --release
    artifacts:
      - tempproject/build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
