workflows:
  android-workflow:
    name: Neon Galeri Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Proje oluştur ve APK al
        script: >-
          flutter create -t app tempproject &&
          cp -r lib tempproject/ &&
          cp pubspec_build.yaml tempproject/pubspec.yaml &&
          cd tempproject &&
          flutter pub get &&
          flutter build apk --release
    artifacts:
      - tempproject/build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
