workflows:
  android-workflow:
    name: Neon Galeri Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Proje oluştur ve APK al
        script: |
          flutter create -t app tempproject
          cp -r lib tempproject/
          cd tempproject
          sed -i 's/sdk: .*/sdk: "^3.11.0"/' pubspec.yaml
          sed -i '/^dependencies:/a\  image_picker: ^1.0.7\n  path_provider: ^2.1.2\n  path: ^1.9.0\n  shared_preferences: ^2.2.2\n  video_player: ^2.8.3' pubspec.yaml
          flutter pub get
          flutter build apk --release
    artifacts:
      - tempproject/build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
