workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Proje oluştur
        script: |
          flutter create -t app tempproject
          cp pubspec.yaml tempproject/pubspec.yaml
          cp -r lib tempproject/
          cd tempproject
          flutter pub get
      - name: APK oluştur
        script: |
          cd tempproject
          flutter build apk --release
    artifacts:
      - tempproject/build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
